# Generated by Django 3.1.2 on 2020-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=200)),
            ],
        ),
    ]
